"""Generic PAP analysis workspace contracts."""

from pap_pilot.engine.analysis.model import (
    ANALYSIS_WORKSPACE_ENGINE_VERSION,
    ANALYSIS_WORKSPACE_FORMAT,
    ANALYSIS_WORKSPACE_FORMAT_VERSION,
    ANALYSIS_WORKSPACE_RECORD_VERSION,
    ANALYSIS_WORKSPACE_SCHEMA_ID,
    ANALYSIS_WORKSPACE_SCHEMA_VERSION,
    AnalysisAvailability,
    AnalysisEvidence,
    AnalysisEvidenceKind,
    AnalysisExperimentReference,
    AnalysisModelError,
    AnalysisNight,
    AnalysisResource,
    AnalysisResourceKind,
    AnalysisTrend,
    AnalysisTrendPoint,
    AnalysisWorkspace,
    analysis_resource_id,
    serialize_analysis_workspace,
)

__all__ = [
    "ANALYSIS_WORKSPACE_ENGINE_VERSION",
    "ANALYSIS_WORKSPACE_FORMAT",
    "ANALYSIS_WORKSPACE_FORMAT_VERSION",
    "ANALYSIS_WORKSPACE_RECORD_VERSION",
    "ANALYSIS_WORKSPACE_SCHEMA_ID",
    "ANALYSIS_WORKSPACE_SCHEMA_VERSION",
    "AnalysisAvailability",
    "AnalysisEvidence",
    "AnalysisEvidenceKind",
    "AnalysisExperimentReference",
    "AnalysisModelError",
    "AnalysisNight",
    "AnalysisResource",
    "AnalysisResourceKind",
    "AnalysisTrend",
    "AnalysisTrendPoint",
    "AnalysisWorkspace",
    "analysis_resource_id",
    "serialize_analysis_workspace",
]
