"""Read-only adapters for external PAP data sources."""

from pap_pilot.adapter.oscar import (
    MissingSchemaVersionError,
    OscarDatabaseError,
    OscarDatabaseOpenError,
    SUPPORTED_SCHEMA_VERSIONS,
    UnsupportedSchemaVersionError,
    open_oscar_database,
)
from pap_pilot.adapter.session_events import (
    EVENT_CHANNELS,
    InvalidSessionEventError,
    OscarEventCompleteness,
    OscarEventKind,
    OscarEventSourceClass,
    OscarObservedEventCount,
    OscarSessionEvent,
    OscarSessionEvents,
    SessionEventsError,
    extract_session_events,
)
from pap_pilot.adapter.session_summary import (
    InvalidSessionSummaryError,
    OscarMachineProvenance,
    OscarProfileProvenance,
    OscarSchemaProvenance,
    OscarSessionBoundaries,
    OscarSessionSettings,
    OscarSessionSummary,
    OscarSettingSource,
    REQUIRED_SETTING_CODES,
    SessionNotFoundError,
    SessionSummaryError,
    extract_session_summary,
)

__all__ = [
    "EVENT_CHANNELS",
    "InvalidSessionEventError",
    "InvalidSessionSummaryError",
    "MissingSchemaVersionError",
    "OscarDatabaseError",
    "OscarDatabaseOpenError",
    "OscarEventCompleteness",
    "OscarEventKind",
    "OscarEventSourceClass",
    "OscarMachineProvenance",
    "OscarObservedEventCount",
    "OscarProfileProvenance",
    "OscarSchemaProvenance",
    "OscarSessionBoundaries",
    "OscarSessionEvent",
    "OscarSessionEvents",
    "OscarSessionSettings",
    "OscarSessionSummary",
    "OscarSettingSource",
    "REQUIRED_SETTING_CODES",
    "SUPPORTED_SCHEMA_VERSIONS",
    "SessionEventsError",
    "SessionNotFoundError",
    "SessionSummaryError",
    "UnsupportedSchemaVersionError",
    "extract_session_events",
    "extract_session_summary",
    "open_oscar_database",
]
