"""Deterministic structured reports independent of UI and AI code."""

from pap_pilot.engine.reports.retrospective import (
    RETROSPECTIVE_EVIDENCE_REPORT_ENGINE_VERSION,
    RETROSPECTIVE_EVIDENCE_REPORT_FORMAT,
    RETROSPECTIVE_EVIDENCE_REPORT_FORMAT_VERSION,
    RETROSPECTIVE_EVIDENCE_REPORT_RECORD_VERSION,
    RETROSPECTIVE_EVIDENCE_REPORT_SCHEMA_ID,
    RETROSPECTIVE_EVIDENCE_REPORT_SCHEMA_VERSION,
    EvidenceAvailability,
    ReportArmSummary,
    ReportClassification,
    ReportEvidenceInventory,
    ReportHistoryEvent,
    ReportKnownChange,
    ReportKnownFact,
    ReportMissingInput,
    ReportOutcome,
    ReportPeriod,
    ReportProvenance,
    ReportRepresentativeInterval,
    RetrospectiveEvidenceReport,
    RetrospectiveEvidenceReportError,
    build_ps_min_retrospective_evidence_report,
    serialize_retrospective_evidence_report,
)

__all__ = [
    "RETROSPECTIVE_EVIDENCE_REPORT_ENGINE_VERSION",
    "RETROSPECTIVE_EVIDENCE_REPORT_FORMAT",
    "RETROSPECTIVE_EVIDENCE_REPORT_FORMAT_VERSION",
    "RETROSPECTIVE_EVIDENCE_REPORT_RECORD_VERSION",
    "RETROSPECTIVE_EVIDENCE_REPORT_SCHEMA_ID",
    "RETROSPECTIVE_EVIDENCE_REPORT_SCHEMA_VERSION",
    "EvidenceAvailability",
    "ReportArmSummary",
    "ReportClassification",
    "ReportEvidenceInventory",
    "ReportHistoryEvent",
    "ReportKnownChange",
    "ReportKnownFact",
    "ReportMissingInput",
    "ReportOutcome",
    "ReportPeriod",
    "ReportProvenance",
    "ReportRepresentativeInterval",
    "RetrospectiveEvidenceReport",
    "RetrospectiveEvidenceReportError",
    "build_ps_min_retrospective_evidence_report",
    "serialize_retrospective_evidence_report",
]
